apiVersion: v1
kind: Service
metadata:
  name: anzol
  namespace: anzol
spec:
  ports:
  - name: "8084"
    port: 8084
    targetPort: 80
  selector:
    app: anzol
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: anzol
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
